#!/bin/sh

# Read YAML front matter in all the modified files for committing,
# and replace "updatedAt:" line to "updatedAt: current date and time"

git diff --cached --name-status | grep "^M" | while read a b; do
  cat $b | sed "/---.*/,/---.*/s/^updatedAt:.*$/updatedAt: $(TZ=Asia/Tokyo date "+%Y-%m-%dT%T")+09:00/" > tmp
  mv tmp $b
  git add $b
done

# Run lint-staged

. "$(dirname "$0")/_/husky.sh"

yarn lint-staged
